// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamSystem.Models;

public partial class Answer
{
    [Key]
    public int Ans_ID { get; set; }

    public int? TrueFalse_ID { get; set; }

    public int? Selected { get; set; }

    public int? StudentExam_ID { get; set; }

    public int? MCQ_ID { get; set; }

    [ForeignKey("MCQ_ID")]
    [InverseProperty("Answers")]
    public virtual MCQQuestion MCQ { get; set; }

    [ForeignKey("StudentExam_ID")]
    [InverseProperty("Answers")]
    public virtual StudentExam StudentExam { get; set; }

    [ForeignKey("TrueFalse_ID")]
    [InverseProperty("Answers")]
    public virtual TrueFalseQuestion TrueFalse { get; set; }
}