// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamSystem.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int Exam_ID { get; set; }

    [StringLength(30)]
    public string Title { get; set; }

    public string Description { get; set; }

    public int? Duration { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<MCQQuestion> MCQQuestions { get; set; } = new List<MCQQuestion>();

    [InverseProperty("Exam")]
    public virtual ICollection<Result> Results { get; set; } = new List<Result>();

    [InverseProperty("Exam")]
    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();

    [InverseProperty("Exam")]
    public virtual ICollection<TrueFalseQuestion> TrueFalseQuestions { get; set; } = new List<TrueFalseQuestion>();
}