// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamSystem.Models;

[Table("MCQQuestion")]
public partial class MCQQuestion
{
    [Key]
    public int MCQ_ID { get; set; }

    public string Body { get; set; }

    public int? Mark { get; set; }

    public int? CorrectAnswer { get; set; }

    public string Option1 { get; set; }

    public string Option2 { get; set; }

    public string Option3 { get; set; }

    public string Option4 { get; set; }

    public int? Exam_ID { get; set; }

    [InverseProperty("MCQ")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("Exam_ID")]
    [InverseProperty("MCQQuestions")]
    public virtual Exam Exam { get; set; }
}