// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamSystem.Models;

[Table("StudentExam")]
public partial class StudentExam
{
    [Key]
    public int StudentExam_ID { get; set; }

    public int? Student_ID { get; set; }

    public int? Exam_ID { get; set; }

    public bool isSubmitted { get; set; }

    [InverseProperty("StudentExam")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("Exam_ID")]
    [InverseProperty("StudentExams")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("Student_ID")]
    [InverseProperty("StudentExams")]
    public virtual User Student { get; set; }
}