// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamSystem.Models;

[Table("TrueFalseQuestion")]
public partial class TrueFalseQuestion
{
    [Key]
    public int TrueFalse_ID { get; set; }

    public string Body { get; set; }

    public int? Mark { get; set; }

    public int? CorrectAnswer { get; set; }

    [StringLength(10)]
    public string Option1 { get; set; }

    [StringLength(10)]
    public string Option2 { get; set; }

    public int? Exam_ID { get; set; }

    [InverseProperty("TrueFalse")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("Exam_ID")]
    [InverseProperty("TrueFalseQuestions")]
    public virtual Exam Exam { get; set; }
}