// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ExamSystem.Models;

[Table("User")]
public partial class User
{
    [Key]
    public int User_ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(255)]
    public string PasswordHash { get; set; }

    [StringLength(30)]
    public string Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Result> Results { get; set; } = new List<Result>();

    [JsonIgnore]
    [InverseProperty("Student")]
    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();
}